spring.application.name=carte-mem
spring.neo4j.uri=neo4j+s://902af741.databases.neo4j.io
spring.neo4j.authentication.username=902af741
spring.neo4j.authentication.password=mAmUJY3xurA_SH_BX5jfqC4L1vVk8Gh2jOW5CmgYZZM

# Setare recomandat? pentru debugging
spring.neo4j.logging.level=INFO